export const STORY_INTELLIGENCE = {
  minBodyStrength: 28,
  maxSlides: 15,
  nightActivityPercent: 30,
  weekendUnusualPercent: 40,
  languageDominancePercent: 40,
  languageEvolutionMinShare: 25,
  repositoryConcentrationPercent: 40,
  streakMinDays: 7,
  comebackQuietDays: 14,
  comebackReboundMin: 15,
  finalPushWindowDays: 21,
  finalPushMinContributions: 12,
  finalPushMinRatio: 1.75,
  finalPushMinShare: 0.18,
  finalPushMinBaseline: 20,
  milestoneThresholds: [100, 500, 1000, 2000, 5000],
  openSourceMinCommits: 5,
  openSourceMinPullRequests: 2,
  commitPersonalityMinMessages: 12,
  commitPersonalityMinShare: 30,
  commitPersonalityFinalMinCount: 4,
  commitPersonalityFinalMinShare: 12,
  commitPersonalityKeywordMinCount: 5,
  commitPersonalityKeywordMinShare: 20,
  spikeMultiplier: 4,
  spikeAbsoluteFloor: 8,
  momentumUpwardRatio: 1.2,
  rhythmMinStrength: 40,
  specialistPercent: 70,
  explorerLanguageCount: 5,
  openSourceOrgCount: 1,
  achievementMax: 4,
  shareableBonus: 100,
  measuredAvailabilityBonus: 100,
  estimatedAvailabilityBonus: 70,
} as const;
